neofetch

EDITOR="nvim"

# Alias
alias dotfiles="git -C ~/dotfiles"
alias cd="z"
alias vim="nvim"
alias vi="nvim"
alias neovim='fzf -m --preview="bat --color=always {}" --bind "enter:become(nvim {+})"'
alias n="clear && neofetch"
alias python="python3"
alias pip="pip3"

# Zsh plugins
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Make zsh tab-completion case insensitive
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
# Ensure that completion is enabled
autoload -U compinit
compinit

# Zoxide init
eval "$(zoxide init zsh)"

# Starship prompt
export STARSHIP_CONFIG="$HOME//.config/starship/starship.toml"
eval "$(starship init zsh)"

# Fzf
source <(fzf --zsh)

# Java
export JAVA_HOME=$(/usr/libexec/java_home -v 21)
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# Old Theme
# eval "$(oh-my-posh init zsh --config $HOME/.poshthemes/custom_jblab_edit.json)"
